### ISSUE TITLE
Change bindings for 'fold heading at cursor' and 'unfold all headings'

### ISSUE THREAD

**Issue by mm-gmbd** [melke/markdown-folder#1]
The two methods utilize very common key bindings:
- 'Fold heading at cursor', **ctrl-p**, is very commonly used for paste.
- 'Unfold all headings', **ctrl-o**, is very commonly used for opening new files.

Maybe moving these to two other **ctrl-alt-[something]** bindings would make more sense.

**Comment by melke** [comment]
Thanks @mm-gmbd 
Since most people will have different keybinding preferences, I removed the keybindings altogether. I have seen that many packages use this approach nowadays, and it makes sense. The bindings are now only a recommendation in the README file.
