### ISSUE TITLE
heading-like lines inside fenced blocks or comments 

### ISSUE THREAD

**Issue by tshort** [melke/markdown-folder#11]
Lines that start with `#` inside of fenced blocks and comments act like real headings. These should not fold and unfold the text that's below the "phantom" headings. Here is an example:

``````
# test heading

hello world

## a second heading

```
# a phantom heading
a: 2
```

more text

# another heading

words...

<!--  
# another phantom heading
this is a comment
-->

# a final heading
``````

One way to fix this might be to include an additional check when checking if a line is a header. Maybe check the class of the line to make sure it isn't "comment block gfm" or "markup".

**Comment by melke** [comment]
Hi @tshort I'm struggling with this one. But it's pretty complicated. Not to find the classes, but to decide exactly when, and when not to do the class-checks. I'll keep working. If you have any more suggestions, I'm glad for any help I can get.
