### ISSUE TITLE
Makes text entry very slow

### ISSUE THREAD

**Issue by monotasker** [melke/markdown-folder#13]
Thanks for writing such an amazingly useful plugin. I'm just having one problem. When I activate markdown-folder and try to work on a very large document the text entry gets very slow. I get lags of up to 2 seconds before keystrokes appear on the screen. When I deactivate the plugin and restart atom the lag disappears. I hope you can help because the folding is really helpful.

(using Atom 1.2.0 on Ubuntu 15.10)

**Comment by melke** [comment]
Thanks for your feedback, it's much appreciated.

The plugin doesn't actually do anything except when folding and unfolding something, so the performance problem is probably something done in the Atom code, for example updating display buffers or something, and the folding makes this a heavy process somehow. So the bad news is that it may be difficult to fix this issue by changing something in the markdown-folder package.

If you don't mind I have some questions:
- How large is the document (how many lines?)
- How "deep" is the document, ie how many headline levels are there? (If there are no secrets in the document, I'd love to get a copy of it)
- Does the performance become bad already when activating the plugin, ie bad performance without anything being folded? Or does it gradually become worse after folding more and more lines?
- Can you reproduce this on other platforms than Ubuntu?

**Comment by melke** [comment]
Closing.
