### ISSUE TITLE
Notice: upcoming retirement of markdown-folder

### ISSUE THREAD

**Issue by tshort** [melke/markdown-folder#23]
Unless someone wants to take over maintenance of this package, I plan to remove it from the atom package list. Failing that, I'll just delete it.

This package has suffered bitrot as the Atom API changed, and I don't use Atom (much) anymore.

**Comment by melke** [comment]
Hi @tshort I totally understand this. I logged into atom.io to see if there is a way to remove the package from the atom.io repository, but it seems like this is impossible using the site at least. Maybe you need to raise an issue with atom.io to remove the package. Let me know if I can help.

**Comment by tshort** [comment]
I think `apm unpublish markdown-folder` should do the trick. I'll try tonight.

**Comment by melke** [comment]
Hi. I actually already sent a request to remove it to Atom support. They
responded just to confirm, and I confirmed. So it will go away any day now
:)

Med vänlig hälsning,

Mats Melke
Stockholm Code Group AB
+46 73 262 87 15

2017-08-09 14:40 GMT+02:00 Tom Short <notifications@github.com>:

**Comment by tshort** [comment]
Okay, great. Thanks, Mats. I'll update the readme, too.

**Comment by melke** [comment]
Hi again. I just got confirmation that the package is now removed from the Atom repo.

**Comment by tshort** [comment]
Thanks!
