### ISSUE TITLE
Folding headings not working

### ISSUE THREAD

**Issue by cjpoor** [melke/markdown-folder#4]
Hi Melke,
I initially got this to work but now cannot make it work again. I have disabled all community packages except linter and restarted. The only menu item for markdown-folder is Toggle but it does nothing.
The menu under Edit->Folding also does nothing except fold those paragraphs that are indented.
Do you have any idea what I am doing wrong here?
Thanks,
Chris.

**Comment by melke** [comment]
Have you tried restarting Atom and closing/reopening the markdown file. There seems to be a bug in Atom 1.0.7 when it restores last used tabs, so the grammar-based packages does not get loaded https://github.com/atom/atom/issues/8313. Please try close/reopen and post the results here.

**Comment by cjpoor** [comment]
Hi Mats,
Restarted Atom and closed and re-opened the md file (I assume "close pane" closes the file if it is not open in another pane or tab).
I expect to see a sub-menu under the "markdown-folder" menu item of "Packages" menu. There is only "toggle" but clicking on it seems to have no effect.
I would like to use markdown-folder because I write prose and the (coding) indentation method is not as intuitive (although I gather it is CommonMark standard).
Anything else I can try?
Chris.

**Comment by melke** [comment]
Hi Chris,

For some reason, I hadn't defined all available commands in the menu. If you update the package now you will get sub menu items for all commands.

Regarding `toggle`: You need to have the cursor on a line that starts with a hash sign. Note that there must also be a space between the hash sign and the heading.

Since it's almost impossible for me to come up with default unique keybindings that suits everyone, I have not defined any keybindings at all. Please add keybindings to your keymap file. Here is a suggestion:

```
'atom-workspace':
  'alt-t': 'markdown-folder:toggle'
  'ctrl-alt-t': 'markdown-folder:unfoldall'
  'ctrl-alt-1': 'markdown-folder:foldall-h1'
  'ctrl-alt-2': 'markdown-folder:foldall-h2'
  'ctrl-alt-3': 'markdown-folder:foldall-h3'
  'ctrl-alt-4': 'markdown-folder:foldall-h4'
  'ctrl-alt-5': 'markdown-folder:foldall-h5'
```

You can edit your keymap file by selecting "Open Your Keymap" from the "Atom" menu.
Good luck and thanks for your feedback!

**Comment by cjpoor** [comment]
Hi Mats,
Thanks for that. I updated and got the menu items but no action.
Tried restarting and reopening. No dice. Does it matter that my sections are indented?
Chris.

**Comment by melke** [comment]
Yes it matters. The lines must start with the hash signs.

**Comment by cjpoor** [comment]
Tried that but didn't try restarting, closing opening. ... Later.

**Comment by melke** [comment]
I didn't quite understand that last comment. Does it work for you now?

**Comment by cjpoor** [comment]
No. Sorry, Mats. I didn't get it to work. I might try again tomorrow on a test document.

**Comment by cjpoor** [comment]
Tried again with a test text. Not working.

**Comment by melke** [comment]
Are you running on Windows or Mac? Which OS version? Can you send me an example file? My email is mats@melke.nu

**Comment by cjpoor** [comment]
I'm running Mac OS X 10.10.3 (14D136)
I'll email you my test file.

**Comment by melke** [comment]
Hi, it works perfectly for me on my Mac. Here you can see how I do it, using the menus https://dl.dropboxusercontent.com/u/5925696/markdownfolder/markdownfolder.mov

Are you sure that you also have the package language-gfm installed? That's a prerequisite for markdown-folder. Can you see the status text "Github markdown" in the lower right corner of the Atom window?

**Comment by cjpoor** [comment]
Hi. Yes I have language-gfm installed (it is a core package). I also have all community packages except markdown-folder and linter disabled. Github markdown is on the status line lower right.
I followed the process you showed on the movie. Thanks for that. It seems that you need to place the cursor on the left of the heading text to fold the text below, and on the left of the hashes to fold the heading itself. I still couldn't do it.
I think there must be a conflict with one of the packages I installed. Disabling probably doesn't revert Atom back to it's original state. Maybe I will need to uninstall all community packages ...

**Comment by cjpoor** [comment]
Plus - Brew doctor tells me I have a slew of problems that I have to fix ... :-\

**Comment by melke** [comment]
Ok, thanks. I'm closing this then.
BTW, it doesn't matter where on the line you have your cursor when folding.

**Comment by cjpoor** [comment]
Hi Mats,
I think my problem was caused by a conflict with Folding Text.
Thanks,
Chris.
