### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by LeoUfimtsev** [melke/markdown-folder#7]
Hello, 

I copied your keybindings from the example into my config.

When I try Ctrl+alt+1, or alt+t, in the command view it shows that the commands are getting executed, but nothing is folder.

Atom 1.0.16 OSX, with markdowh-folder 0.3.0

Please advise.

**Comment by jonleung** [comment]
This doesn't work for me either...

See the following screen capture:

![](https://s3.amazonaws.com/f.cl.ly/items/0K1z0a04053J3s1O121i/Screen%20Recording%202015-10-03%20at%2011.05%20AM.gif)

**Comment by tshort** [comment]
This works for me on both Windows and Linux. Looks like it might be a Mac-specific problem.

**Comment by melke** [comment]
Hi, thanks for reporting. There seems to be a bug, where the package is never activated when the tab was already opened since last time Atom was used.

Can you try closing and reopening the markdown file?

**Comment by melke** [comment]
There is an Atom bug, that prevents packages loaded by grammar-used to load when reopening Atom. A fix is ready, but the Atom team hasn't merged it yet. https://github.com/atom/atom/pull/8692
When this fix has been released, upgrade Atom and it start working. Until then, the workaround is to close and open the markdown file again after starting Atom with already opened tabs.

**Comment by melke** [comment]
Instead of waiting for the #8692 in the Atom repo, I decided to abandon grammar-based loading of the package. Instead, the package is loaded whenever a markdown-folder command is used.
